### ISSUE TITLE
Normalize Whitespace

### ISSUE THREAD

**Issue by AnatoliyAkhmatov** [iFallUpHill/gulp-prism#1]
Hi! Is it possible to normalize the whitespace as in the original prism.js?

**Comment by iFallUpHill** [comment]
Currently there is no plugin support but it's definitely something that I would like to have in the future. 

For now, the best solution would be to just treat this as a syntax highlighter that solely adds highlighting to properly formatted code (i.e. format the code blocks as if you were going to show it without highlighting).

**Comment by AnatoliyAkhmatov** [comment]
Great, when do you plan to add plugins?

**Comment by iFallUpHill** [comment]
@Juuly I haven't looked into it much, but I would have to spend some time looking into how to best allow plugins to be enabled / disabled as well as how to make them configurable through gulp. Truthfully I'm not sure how long it would take as I don't use any plugins myself. I'm open to merging PRs if you have any thoughts about how to get started with this though!
